databases:
  - name: myprojectdb
    plan: free
    databaseName: myproject
    user: myproject

services:
  - type: web
    plan: free
    name: myproject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn myProject.wsgi:application"  # Update this as needed
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myprojectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
