databases:
  - name: myprojectdb
    plan: free
    databaseName: myProject
    user: myProjectUser

services:
  - type: web
    plan: free
    name: myproject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn myProject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myprojectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
