# Generated by Django 3.2.1 on 2024-09-26 23:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('media', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('order', models.IntegerField(default=0)),
                ('font', models.CharField(default='Arial', max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='myApp.portfolio')),
            ],
        ),
    ]
