# Generated by Django 3.2.1 on 2024-09-27 09:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0002_portfolio_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('description', ckeditor.fields.RichTextField()),
                ('background_nationality', models.CharField(max_length=100)),
                ('background_hometown', models.CharField(max_length=100)),
                ('background_languages', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
