# Generated by Django 3.2.1 on 2024-09-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_aboutme_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
